name: publish
on: 
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types:
    - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-restore

  build:
    runs-on: ubuntu-latest
    needs: [ tests ]

    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: 6.x

    - name: Determine version with GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Restore
      run: dotnet restore
        
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
    - run: dotnet pack ${{github.workspace}}/src/FlintSoft.CQRS/FlintSoft.CQRS.csproj --configuration Release --output ${{env.NuGetDirectory}} -p:PackageVersion=${{ env.semVer }} -p:Version=${{ env.semVer }} -p:AssemblyVersion=${{ env.semVer }}
  
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{env.NuGetDirectory}}/*.nupkg

  deploy:
    runs-on: ubuntu-latest
    needs: [ tests, build ]
    permissions:
      id-token: write
      
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{env.NuGetDirectory}}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: mprattinger # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address

      - name: Publish to NuGet
        run: dotnet nuget push ${{env.NuGetDirectory}}/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
